In [24]:
!ls ~/data/cifar-10-python/cifar-10-batches-py/


batches.meta  data_batch_2  data_batch_4  readme.html
data_batch_1  data_batch_3  data_batch_5  test_batch


In [28]:
from pickle import load
from numpy import concatenate,array
from pathlib import Path
labs=[]
data=[]
for f in [str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/data_batch_'+str(i) for i in range(1,6)]:
  with open(f,'rb') as fd:
    raw=load(fd,encoding='bytes')
    data.append(raw[b'data'])
    labs.append(array(raw[b'labels']))

with open(str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/test_batch','rb') as fd:
  raw=load(fd,encoding='bytes')
  X_test=raw[b'data']
  y_test=array(raw[b'labels'])
  

print('Each batch has data shape:',raw[b'data'].shape)
print('Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image')
X=concatenate(data)
y=concatenate(labs)


Each batch has data shape: (10000, 3072)
Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image


In [17]:
print(X[:10])
print(y[:10])

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 28  30  33 ... 100  99  96]
 [134 131 128 ... 136 137 138]
 [125 110 102 ...  82  84  86]]
[6 9 9 4 1 1 2 7 8 3]
