In [1]:
!ls ~/data/cifar-10-python/cifar-10-batches-py/


batches.meta  data_batch_2  data_batch_4  readme.html
data_batch_1  data_batch_3  data_batch_5  test_batch


In [2]:
from pickle import load
from numpy import concatenate,array,float32
from pathlib import Path
labs=[]
data=[]
for f in [str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/data_batch_'+str(i) for i in range(1,6)]:
  with open(f,'rb') as fd:
    raw=load(fd,encoding='bytes')
    data.append(raw[b'data'])
    labs.append(array(raw[b'labels']))

X=concatenate(data)
y=(concatenate(labs)==0).astype(float32)
    
with open(str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/test_batch','rb') as fd:
  raw=load(fd,encoding='bytes')
  X_test=raw[b'data']
  y_test=(array(raw[b'labels'])==0).astype(float32)
  

print('Each batch has data shape:',raw[b'data'].shape)
print('Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image')



Each batch has data shape: (10000, 3072)
Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image


In [3]:
print(X[:10])
print(y[:10])

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 28  30  33 ... 100  99  96]
 [134 131 128 ... 136 137 138]
 [125 110 102 ...  82  84  86]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
'''from cal.jaxn import bin_optimiser
hlp=bin_optimiser(X.shape[1],kappa=.99,beta=2)
hlp.bench(X_test,y_test)
hlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)
hlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)
hlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)
hlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)
hlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)
hlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)'''

'from cal.jaxn import bin_optimiser\nhlp=bin_optimiser(X.shape[1],kappa=.99,beta=2)\nhlp.bench(X_test,y_test)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)'

In [5]:
from cal.jaxn import bin_optimiser,nlp_infer_v,nlp_init_params
hlp=bin_optimiser(X.shape[1],kappa=.99,beta=2,implementation=nlp_infer_v,init_params=nlp_init_params)
hlp.bench(X_test,y_test)
hlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)
hlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)
hlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)
hlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)
hlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)
hlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)

ValueError: Comparator raised exception while sorting pytree dictionary keys.