In [1]:
!ls ~/data/cifar-10-python/cifar-10-batches-py/


batches.meta  data_batch_2  data_batch_4  readme.html
data_batch_1  data_batch_3  data_batch_5  test_batch


In [2]:
from pickle import load
from numpy import concatenate,array,float32
from pathlib import Path
labs=[]
data=[]
for f in [str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/data_batch_'+str(i) for i in range(1,6)]:
  with open(f,'rb') as fd:
    raw=load(fd,encoding='bytes')
    data.append(raw[b'data'])
    labs.append(array(raw[b'labels']))

X=concatenate(data)
y=(concatenate(labs)==0).astype(float32)
    
with open(str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/test_batch','rb') as fd:
  raw=load(fd,encoding='bytes')
  X_test=raw[b'data']
  y_test=(array(raw[b'labels'])==0).astype(float32)
  

print('Each batch has data shape:',raw[b'data'].shape)
print('Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image')



Each batch has data shape: (10000, 3072)
Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image


In [3]:
print(X[:10])
print(y[:10])

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 28  30  33 ... 100  99  96]
 [134 131 128 ... 136 137 138]
 [125 110 102 ...  82  84  86]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
'''from cal.jaxn import bin_optimiser
hlp=bin_optimiser(X.shape[1],kappa=.99,beta=2)
hlp.bench(X_test,y_test)
hlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)
hlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)
hlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)
hlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)
hlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)
hlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)'''

'from cal.jaxn import bin_optimiser\nhlp=bin_optimiser(X.shape[1],kappa=.99,beta=2)\nhlp.bench(X_test,y_test)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)'

In [5]:
from cal.jaxn import bin_optimiser,mk_nlp_infer,mk_nlp_init_params
hlp=bin_optimiser(X.shape[1],kappa=.9,beta=.7,implementation=mk_nlp_infer(),init_params=mk_nlp_init_params())
hlp.bench(X_test,y_test)

hlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=200)
hlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=100)
hlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=50)

[bin,cts] tp: [0.10000,0.08790]
[bin,cts] fp: [0.90000,0.79268]
[bin,cts] fn: [0.00000,0.01210]
[bin,cts,tgt] fp/fn: [       inf,  65.49657,   0.49000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 0.00000
Beginning epoch 1 ...
Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.10000,0.08772]
[bin,cts] fp: [0.90000,0.79178]
[bin,cts] fn: [0.00000,0.01228]
[bin,cts,tgt] fp/fn: [       inf,  64.47013,   0.49000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 1.33929
Epoch 1.2804097311139564 % complete... training performance:
[bin,cts] tp: [0.10000,0.08509]
[bin,cts] fp: [0.90000,0.76839]
[bin,cts] fn: [0.00000,0.01491]
[bin,cts,tgt] fp/fn: [       inf,  51.54477,   0.49000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 9.22972
Epoch 9.98719590268886 % complete... training performance:
[bin,cts] tp: [0.09972,0.06198]
[bin,cts] fp: [0.89730,0.56150]
[bin,cts] fn: [0.00028,0.03802]
[bin,cts,tgt] fp/fn: [3204.64307,  14.76943,   0.49000]
bin pr:0.10002
bin rc:0.99720
fp wgt: 13.94759
Epoch 11.2676056338

Epoch 41.2291933418694 % complete... training performance:
[bin,cts] tp: [0.00436,0.04012]
[bin,cts] fp: [0.04986,0.36483]
[bin,cts] fn: [0.09564,0.05988]
[bin,cts,tgt] fp/fn: [   0.52133,   6.09290,   0.49000]
bin pr:0.08041
bin rc:0.04360
fp wgt: 0.23483
Epoch 49.9359795134443 % complete... training performance:
[bin,cts] tp: [0.00374,0.03963]
[bin,cts] fp: [0.04320,0.36004]
[bin,cts] fn: [0.09626,0.06037]
[bin,cts,tgt] fp/fn: [   0.44878,   5.96416,   0.49000]
bin pr:0.07968
bin rc:0.03740
fp wgt: 0.11202
Epoch 51.21638924455826 % complete... training performance:
[bin,cts] tp: [0.00360,0.03949]
[bin,cts] fp: [0.04160,0.35872]
[bin,cts] fn: [0.09640,0.06051]
[bin,cts,tgt] fp/fn: [   0.43154,   5.92844,   0.49000]
bin pr:0.07965
bin rc:0.03600
fp wgt: 0.34002
Epoch 59.92317541613317 % complete... training performance:
[bin,cts] tp: [0.00302,0.03902]
[bin,cts] fp: [0.03540,0.35444]
[bin,cts] fn: [0.09698,0.06098]
[bin,cts,tgt] fp/fn: [   0.36502,   5.81248,   0.49000]
bin pr:0.07860
b

Epoch 89.88476312419974 % complete... training performance:
[bin,cts] tp: [0.00458,0.04102]
[bin,cts] fp: [0.05102,0.37204]
[bin,cts] fn: [0.09542,0.05898]
[bin,cts,tgt] fp/fn: [   0.53469,   6.30769,   0.49000]
bin pr:0.08237
bin rc:0.04580
fp wgt: 0.19743
Epoch 91.1651728553137 % complete... training performance:
[bin,cts] tp: [0.00434,0.04085]
[bin,cts] fp: [0.04814,0.37047]
[bin,cts] fn: [0.09566,0.05915]
[bin,cts,tgt] fp/fn: [   0.50324,   6.26334,   0.49000]
bin pr:0.08270
bin rc:0.04340
fp wgt: 0.20216
Epoch 99.8719590268886 % complete... training performance:
[bin,cts] tp: [0.00424,0.04118]
[bin,cts] fp: [0.04614,0.37318]
[bin,cts] fn: [0.09576,0.05882]
[bin,cts,tgt] fp/fn: [   0.48183,   6.34471,   0.49000]
bin pr:0.08416
bin rc:0.04240
fp wgt: -0.55309
...done!
Training performance:
[bin,cts] tp: [0.00424,0.04118]
[bin,cts] fp: [0.04614,0.37318]
[bin,cts] fn: [0.09576,0.05882]
[bin,cts,tgt] fp/fn: [   0.48183,   6.34471,   0.49000]
bin pr:0.08416
bin rc:0.04240
fp wgt: -0.553

Epoch 21.254801536491676 % complete... training performance:
[bin,cts] tp: [0.00622,0.04331]
[bin,cts] fp: [0.06856,0.39234]
[bin,cts] fn: [0.09378,0.05669]
[bin,cts,tgt] fp/fn: [   0.73107,   6.92136,   0.49000]
bin pr:0.08318
bin rc:0.06220
fp wgt: -0.54398
Epoch 29.961587708066585 % complete... training performance:
[bin,cts] tp: [0.00696,0.04363]
[bin,cts] fp: [0.07594,0.39524]
[bin,cts] fn: [0.09304,0.05637]
[bin,cts,tgt] fp/fn: [   0.81621,   7.01186,   0.49000]
bin pr:0.08396
bin rc:0.06960
fp wgt: 0.34363
Epoch 31.241997439180537 % complete... training performance:
[bin,cts] tp: [0.00664,0.04337]
[bin,cts] fp: [0.07204,0.39285]
[bin,cts] fn: [0.09336,0.05663]
[bin,cts,tgt] fp/fn: [   0.77164,   6.93681,   0.49000]
bin pr:0.08439
bin rc:0.06640
fp wgt: 0.24197
Epoch 39.94878361075544 % complete... training performance:
[bin,cts] tp: [0.00532,0.04236]
[bin,cts] fp: [0.05802,0.38397]
[bin,cts] fn: [0.09468,0.05764]
[bin,cts,tgt] fp/fn: [   0.61280,   6.66176,   0.49000]
bin pr:0.0

Epoch 69.91037131882202 % complete... training performance:
[bin,cts] tp: [0.00400,0.04184]
[bin,cts] fp: [0.04326,0.37861]
[bin,cts] fn: [0.09600,0.05816]
[bin,cts,tgt] fp/fn: [   0.45063,   6.51000,   0.49000]
bin pr:0.08464
bin rc:0.04000
fp wgt: -0.02777
Epoch 71.19078104993598 % complete... training performance:
[bin,cts] tp: [0.00404,0.04182]
[bin,cts] fp: [0.04334,0.37841]
[bin,cts] fn: [0.09596,0.05818]
[bin,cts,tgt] fp/fn: [   0.45165,   6.50403,   0.49000]
bin pr:0.08527
bin rc:0.04040
fp wgt: -0.01101
Epoch 79.89756722151088 % complete... training performance:
[bin,cts] tp: [0.00410,0.04156]
[bin,cts] fp: [0.04252,0.37604]
[bin,cts] fn: [0.09590,0.05844]
[bin,cts,tgt] fp/fn: [   0.44338,   6.43495,   0.49000]
bin pr:0.08795
bin rc:0.04100
fp wgt: -0.20327
Epoch 81.17797695262485 % complete... training performance:
[bin,cts] tp: [0.00426,0.04167]
[bin,cts] fp: [0.04388,0.37701]
[bin,cts] fn: [0.09574,0.05833]
[bin,cts,tgt] fp/fn: [   0.45832,   6.46356,   0.49000]
bin pr:0.08

Epoch 1.2804097311139564 % complete... training performance:
[bin,cts] tp: [0.00772,0.04479]
[bin,cts] fp: [0.07994,0.40451]
[bin,cts] fn: [0.09228,0.05521]
[bin,cts,tgt] fp/fn: [   0.86628,   7.32650,   0.49000]
bin pr:0.08807
bin rc:0.07720
fp wgt: 0.13719
Epoch 9.98719590268886 % complete... training performance:
[bin,cts] tp: [0.00678,0.04442]
[bin,cts] fp: [0.06934,0.40106]
[bin,cts] fn: [0.09322,0.05558]
[bin,cts,tgt] fp/fn: [   0.74383,   7.21578,   0.49000]
bin pr:0.08907
bin rc:0.06780
fp wgt: 0.11075
Epoch 11.267605633802818 % complete... training performance:
[bin,cts] tp: [0.00652,0.04430]
[bin,cts] fp: [0.06660,0.39994]
[bin,cts] fn: [0.09348,0.05570]
[bin,cts,tgt] fp/fn: [   0.71245,   7.17986,   0.49000]
bin pr:0.08917
bin rc:0.06520
fp wgt: 0.18400
Epoch 19.97439180537772 % complete... training performance:
[bin,cts] tp: [0.00638,0.04423]
[bin,cts] fp: [0.06486,0.39941]
[bin,cts] fn: [0.09362,0.05577]
[bin,cts,tgt] fp/fn: [   0.69280,   7.16170,   0.49000]
bin pr:0.0895

Epoch 49.9359795134443 % complete... training performance:
[bin,cts] tp: [0.00520,0.04288]
[bin,cts] fp: [0.05326,0.38717]
[bin,cts] fn: [0.09480,0.05712]
[bin,cts,tgt] fp/fn: [   0.56181,   6.77848,   0.49000]
bin pr:0.08895
bin rc:0.05200
fp wgt: -0.03739
Epoch 51.21638924455826 % complete... training performance:
[bin,cts] tp: [0.00524,0.04288]
[bin,cts] fp: [0.05360,0.38717]
[bin,cts] fn: [0.09476,0.05712]
[bin,cts,tgt] fp/fn: [   0.56564,   6.77850,   0.49000]
bin pr:0.08906
bin rc:0.05240
fp wgt: 0.05017
Epoch 59.92317541613317 % complete... training performance:
[bin,cts] tp: [0.00446,0.04225]
[bin,cts] fp: [0.04436,0.38148]
[bin,cts] fn: [0.09554,0.05775]
[bin,cts,tgt] fp/fn: [   0.46431,   6.60619,   0.49000]
bin pr:0.09136
bin rc:0.04460
fp wgt: -0.12720
Epoch 61.20358514724712 % complete... training performance:
[bin,cts] tp: [0.00444,0.04230]
[bin,cts] fp: [0.04446,0.38186]
[bin,cts] fn: [0.09556,0.05770]
[bin,cts,tgt] fp/fn: [   0.46526,   6.61760,   0.49000]
bin pr:0.0908

Epoch 91.1651728553137 % complete... training performance:
[bin,cts] tp: [0.00666,0.04366]
[bin,cts] fp: [0.06608,0.39384]
[bin,cts] fn: [0.09334,0.05634]
[bin,cts,tgt] fp/fn: [   0.70795,   6.98992,   0.49000]
bin pr:0.09156
bin rc:0.06660
fp wgt: -0.48500
Epoch 99.8719590268886 % complete... training performance:
[bin,cts] tp: [0.01182,0.04606]
[bin,cts] fp: [0.11742,0.41578]
[bin,cts] fn: [0.08818,0.05394]
[bin,cts,tgt] fp/fn: [   1.33159,   7.70863,   0.49000]
bin pr:0.09146
bin rc:0.11820
fp wgt: -0.15505
...done!
Training performance:
[bin,cts] tp: [0.01182,0.04606]
[bin,cts] fp: [0.11742,0.41578]
[bin,cts] fn: [0.08818,0.05394]
[bin,cts,tgt] fp/fn: [   1.33159,   7.70863,   0.49000]
bin pr:0.09146
bin rc:0.11820
fp wgt: -0.15505
Testing performance:
[bin,cts] tp: [0.01020,0.04584]
[bin,cts] fp: [0.11590,0.41608]
[bin,cts] fn: [0.08980,0.05416]
[bin,cts,tgt] fp/fn: [   1.29065,   7.68236,   0.49000]
bin pr:0.08089
bin rc:0.10200
fp wgt: -0.15505
Beginning epoch 11 ...
Epoch 0.0 %

Epoch 29.961587708066585 % complete... training performance:
[bin,cts] tp: [0.00968,0.04499]
[bin,cts] fp: [0.09662,0.40662]
[bin,cts] fn: [0.09032,0.05501]
[bin,cts,tgt] fp/fn: [   1.06975,   7.39241,   0.49000]
bin pr:0.09106
bin rc:0.09680
fp wgt: -0.09954
Epoch 31.241997439180537 % complete... training performance:
[bin,cts] tp: [0.00986,0.04507]
[bin,cts] fp: [0.09832,0.40732]
[bin,cts] fn: [0.09014,0.05493]
[bin,cts,tgt] fp/fn: [   1.09075,   7.41493,   0.49000]
bin pr:0.09114
bin rc:0.09860
fp wgt: -0.02366
Epoch 39.94878361075544 % complete... training performance:
[bin,cts] tp: [0.00790,0.04406]
[bin,cts] fp: [0.07902,0.39835]
[bin,cts] fn: [0.09210,0.05594]
[bin,cts,tgt] fp/fn: [   0.85798,   7.12100,   0.49000]
bin pr:0.09089
bin rc:0.07900
fp wgt: 0.16470
Epoch 41.2291933418694 % complete... training performance:
[bin,cts] tp: [0.00740,0.04385]
[bin,cts] fp: [0.07532,0.39648]
[bin,cts] fn: [0.09260,0.05615]
[bin,cts,tgt] fp/fn: [   0.81339,   7.06130,   0.49000]
bin pr:0.08

Epoch 71.19078104993598 % complete... training performance:
[bin,cts] tp: [0.00736,0.04324]
[bin,cts] fp: [0.07644,0.39104]
[bin,cts] fn: [0.09264,0.05676]
[bin,cts,tgt] fp/fn: [   0.82513,   6.88962,   0.49000]
bin pr:0.08783
bin rc:0.07360
fp wgt: -0.26898
Epoch 79.89756722151088 % complete... training performance:
[bin,cts] tp: [0.00676,0.04263]
[bin,cts] fp: [0.06986,0.38546]
[bin,cts] fn: [0.09324,0.05737]
[bin,cts,tgt] fp/fn: [   0.74925,   6.71856,   0.49000]
bin pr:0.08823
bin rc:0.06760
fp wgt: 0.19246
Epoch 81.17797695262485 % complete... training performance:
[bin,cts] tp: [0.00656,0.04242]
[bin,cts] fp: [0.06668,0.38354]
[bin,cts] fn: [0.09344,0.05758]
[bin,cts,tgt] fp/fn: [   0.71361,   6.66048,   0.49000]
bin pr:0.08957
bin rc:0.06560
fp wgt: 0.12253
Epoch 89.88476312419974 % complete... training performance:
[bin,cts] tp: [0.00652,0.04241]
[bin,cts] fp: [0.06720,0.38348]
[bin,cts] fn: [0.09348,0.05759]
[bin,cts,tgt] fp/fn: [   0.71887,   6.65865,   0.49000]
bin pr:0.0884

Epoch 9.98719590268886 % complete... training performance:
[bin,cts] tp: [0.00498,0.04146]
[bin,cts] fp: [0.05522,0.37413]
[bin,cts] fn: [0.09502,0.05854]
[bin,cts,tgt] fp/fn: [   0.58114,   6.39089,   0.49000]
bin pr:0.08272
bin rc:0.04980
fp wgt: 0.05668
Epoch 11.267605633802818 % complete... training performance:
[bin,cts] tp: [0.00474,0.04128]
[bin,cts] fp: [0.05312,0.37252]
[bin,cts] fn: [0.09526,0.05872]
[bin,cts,tgt] fp/fn: [   0.55763,   6.34455,   0.49000]
bin pr:0.08192
bin rc:0.04740
fp wgt: 0.16515
Epoch 19.97439180537772 % complete... training performance:
[bin,cts] tp: [0.00540,0.04173]
[bin,cts] fp: [0.05960,0.37706]
[bin,cts] fn: [0.09460,0.05827]
[bin,cts,tgt] fp/fn: [   0.63002,   6.47106,   0.49000]
bin pr:0.08308
bin rc:0.05400
fp wgt: -0.45358
Epoch 21.254801536491676 % complete... training performance:
[bin,cts] tp: [0.00608,0.04206]
[bin,cts] fp: [0.06486,0.38008]
[bin,cts] fn: [0.09392,0.05794]
[bin,cts,tgt] fp/fn: [   0.69059,   6.55927,   0.49000]
bin pr:0.085

Epoch 51.21638924455826 % complete... training performance:
[bin,cts] tp: [0.00626,0.04087]
[bin,cts] fp: [0.06636,0.36933]
[bin,cts] fn: [0.09374,0.05913]
[bin,cts,tgt] fp/fn: [   0.70792,   6.24579,   0.49000]
bin pr:0.08620
bin rc:0.06260
fp wgt: 0.45674
Epoch 59.92317541613317 % complete... training performance:
[bin,cts] tp: [0.00524,0.04004]
[bin,cts] fp: [0.05536,0.36154]
[bin,cts] fn: [0.09476,0.05996]
[bin,cts,tgt] fp/fn: [   0.58421,   6.03003,   0.49000]
bin pr:0.08647
bin rc:0.05240
fp wgt: 0.08828
Epoch 61.20358514724712 % complete... training performance:
[bin,cts] tp: [0.00502,0.03995]
[bin,cts] fp: [0.05424,0.36064]
[bin,cts] fn: [0.09498,0.06005]
[bin,cts,tgt] fp/fn: [   0.57107,   6.00541,   0.49000]
bin pr:0.08471
bin rc:0.05020
fp wgt: 0.26217
Epoch 69.91037131882202 % complete... training performance:
[bin,cts] tp: [0.00432,0.03892]
[bin,cts] fp: [0.04586,0.35128]
[bin,cts] fn: [0.09568,0.06108]
[bin,cts,tgt] fp/fn: [   0.47931,   5.75118,   0.49000]
bin pr:0.08609

Epoch 99.8719590268886 % complete... training performance:
[bin,cts] tp: [0.00736,0.04116]
[bin,cts] fp: [0.07824,0.37191]
[bin,cts] fn: [0.09264,0.05884]
[bin,cts,tgt] fp/fn: [   0.84456,   6.32017,   0.49000]
bin pr:0.08598
bin rc:0.07360
fp wgt: -0.01657
...done!
Training performance:
[bin,cts] tp: [0.00736,0.04116]
[bin,cts] fp: [0.07824,0.37191]
[bin,cts] fn: [0.09264,0.05884]
[bin,cts,tgt] fp/fn: [   0.84456,   6.32017,   0.49000]
bin pr:0.08598
bin rc:0.07360
fp wgt: -0.01657
Testing performance:
[bin,cts] tp: [0.00800,0.04106]
[bin,cts] fp: [0.07490,0.37086]
[bin,cts] fn: [0.09200,0.05894]
[bin,cts,tgt] fp/fn: [   0.81413,   6.29234,   0.49000]
bin pr:0.09650
bin rc:0.08000
fp wgt: -0.01657
Beginning epoch 18 ...
Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.00736,0.04117]
[bin,cts] fp: [0.07848,0.37200]
[bin,cts] fn: [0.09264,0.05883]
[bin,cts,tgt] fp/fn: [   0.84715,   6.32277,   0.49000]
bin pr:0.08574
bin rc:0.07360
fp wgt: 0.05294
Epoch 1.2804097311139564 

Epoch 31.241997439180537 % complete... training performance:
[bin,cts] tp: [0.00634,0.03982]
[bin,cts] fp: [0.06412,0.35998]
[bin,cts] fn: [0.09366,0.06018]
[bin,cts,tgt] fp/fn: [   0.68460,   5.98123,   0.49000]
bin pr:0.08998
bin rc:0.06340
fp wgt: 0.10913
Epoch 39.94878361075544 % complete... training performance:
[bin,cts] tp: [0.00634,0.03963]
[bin,cts] fp: [0.06472,0.35875]
[bin,cts] fn: [0.09366,0.06037]
[bin,cts,tgt] fp/fn: [   0.69101,   5.94265,   0.49000]
bin pr:0.08922
bin rc:0.06340
fp wgt: -0.12324
Epoch 41.2291933418694 % complete... training performance:
[bin,cts] tp: [0.00642,0.03968]
[bin,cts] fp: [0.06594,0.35927]
[bin,cts] fn: [0.09358,0.06032]
[bin,cts,tgt] fp/fn: [   0.70464,   5.95642,   0.49000]
bin pr:0.08872
bin rc:0.06420
fp wgt: -0.16043
Epoch 49.9359795134443 % complete... training performance:
[bin,cts] tp: [0.00658,0.03962]
[bin,cts] fp: [0.06740,0.35844]
[bin,cts] fn: [0.09342,0.06038]
[bin,cts,tgt] fp/fn: [   0.72147,   5.93615,   0.49000]
bin pr:0.0889

Epoch 79.89756722151088 % complete... training performance:
[bin,cts] tp: [0.00558,0.03854]
[bin,cts] fp: [0.05546,0.34863]
[bin,cts] fn: [0.09442,0.06146]
[bin,cts,tgt] fp/fn: [   0.58738,   5.67289,   0.49000]
bin pr:0.09142
bin rc:0.05580
fp wgt: -0.10975
Epoch 81.17797695262485 % complete... training performance:
[bin,cts] tp: [0.00568,0.03860]
[bin,cts] fp: [0.05664,0.34922]
[bin,cts] fn: [0.09432,0.06140]
[bin,cts,tgt] fp/fn: [   0.60051,   5.68768,   0.49000]
bin pr:0.09114
bin rc:0.05680
fp wgt: -0.10951
Epoch 89.88476312419974 % complete... training performance:
[bin,cts] tp: [0.00596,0.03877]
[bin,cts] fp: [0.06048,0.35125]
[bin,cts] fn: [0.09404,0.06123]
[bin,cts,tgt] fp/fn: [   0.64313,   5.73662,   0.49000]
bin pr:0.08970
bin rc:0.05960
fp wgt: -0.23871
Epoch 91.1651728553137 % complete... training performance:
[bin,cts] tp: [0.00598,0.03890]
[bin,cts] fp: [0.06092,0.35238]
[bin,cts] fn: [0.09402,0.06110]
[bin,cts,tgt] fp/fn: [   0.64795,   5.76704,   0.49000]
bin pr:0.089

Epoch 11.267605633802818 % complete... training performance:
[bin,cts] tp: [0.00444,0.03841]
[bin,cts] fp: [0.04310,0.34701]
[bin,cts] fn: [0.09556,0.06159]
[bin,cts,tgt] fp/fn: [   0.45103,   5.63452,   0.49000]
bin pr:0.09340
bin rc:0.04440
fp wgt: 0.22356
Epoch 19.97439180537772 % complete... training performance:
[bin,cts] tp: [0.00410,0.03797]
[bin,cts] fp: [0.04162,0.34331]
[bin,cts] fn: [0.09590,0.06203]
[bin,cts,tgt] fp/fn: [   0.43399,   5.53482,   0.49000]
bin pr:0.08968
bin rc:0.04100
fp wgt: -0.37231
Epoch 21.254801536491676 % complete... training performance:
[bin,cts] tp: [0.00430,0.03823]
[bin,cts] fp: [0.04406,0.34569]
[bin,cts] fn: [0.09570,0.06177]
[bin,cts,tgt] fp/fn: [   0.46040,   5.59645,   0.49000]
bin pr:0.08892
bin rc:0.04300
fp wgt: -0.33211
Epoch 29.961587708066585 % complete... training performance:
[bin,cts] tp: [0.00578,0.03999]
[bin,cts] fp: [0.05784,0.36158]
[bin,cts] fn: [0.09422,0.06001]
[bin,cts,tgt] fp/fn: [   0.61388,   6.02552,   0.49000]
bin pr:0.

Epoch 59.92317541613317 % complete... training performance:
[bin,cts] tp: [0.00692,0.04135]
[bin,cts] fp: [0.06932,0.37395]
[bin,cts] fn: [0.09308,0.05865]
[bin,cts,tgt] fp/fn: [   0.74474,   6.37588,   0.49000]
bin pr:0.09077
bin rc:0.06920
fp wgt: 0.06719
Epoch 61.20358514724712 % complete... training performance:
[bin,cts] tp: [0.00688,0.04129]
[bin,cts] fp: [0.06870,0.37338]
[bin,cts] fn: [0.09312,0.05871]
[bin,cts,tgt] fp/fn: [   0.73776,   6.35957,   0.49000]
bin pr:0.09103
bin rc:0.06880
fp wgt: 0.35940
Epoch 69.91037131882202 % complete... training performance:
[bin,cts] tp: [0.00562,0.04011]
[bin,cts] fp: [0.05704,0.36260]
[bin,cts] fn: [0.09438,0.05989]
[bin,cts,tgt] fp/fn: [   0.60437,   6.05474,   0.49000]
bin pr:0.08969
bin rc:0.05620
fp wgt: -0.08502
Epoch 71.19078104993598 % complete... training performance:
[bin,cts] tp: [0.00562,0.04014]
[bin,cts] fp: [0.05722,0.36289]
[bin,cts] fn: [0.09438,0.05986]
[bin,cts,tgt] fp/fn: [   0.60627,   6.06262,   0.49000]
bin pr:0.0894

Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.00664,0.04167]
[bin,cts] fp: [0.06798,0.37714]
[bin,cts] fn: [0.09336,0.05833]
[bin,cts,tgt] fp/fn: [   0.72815,   6.46587,   0.49000]
bin pr:0.08898
bin rc:0.06640
fp wgt: 0.04401
Epoch 1.2804097311139564 % complete... training performance:
[bin,cts] tp: [0.00660,0.04157]
[bin,cts] fp: [0.06636,0.37606]
[bin,cts] fn: [0.09340,0.05843]
[bin,cts,tgt] fp/fn: [   0.71049,   6.43558,   0.49000]
bin pr:0.09046
bin rc:0.06600
fp wgt: 0.34010
Epoch 9.98719590268886 % complete... training performance:
[bin,cts] tp: [0.00502,0.04040]
[bin,cts] fp: [0.04876,0.36478]
[bin,cts] fn: [0.09498,0.05960]
[bin,cts,tgt] fp/fn: [   0.51337,   6.12034,   0.49000]
bin pr:0.09334
bin rc:0.05020
fp wgt: 0.00787
Epoch 11.267605633802818 % complete... training performance:
[bin,cts] tp: [0.00492,0.04023]
[bin,cts] fp: [0.04654,0.36323]
[bin,cts] fn: [0.09508,0.05977]
[bin,cts,tgt] fp/fn: [   0.48948,   6.07735,   0.49000]
bin pr:0.09561
bin rc:0.049

Epoch 41.2291933418694 % complete... training performance:
[bin,cts] tp: [0.00748,0.04317]
[bin,cts] fp: [0.07540,0.39079]
[bin,cts] fn: [0.09252,0.05683]
[bin,cts,tgt] fp/fn: [   0.81496,   6.87618,   0.49000]
bin pr:0.09025
bin rc:0.07480
fp wgt: 0.06429
Epoch 49.9359795134443 % complete... training performance:
[bin,cts] tp: [0.00626,0.04214]
[bin,cts] fp: [0.06540,0.38136]
[bin,cts] fn: [0.09374,0.05786]
[bin,cts,tgt] fp/fn: [   0.69767,   6.59063,   0.49000]
bin pr:0.08736
bin rc:0.06260
fp wgt: 0.27667
Epoch 51.21638924455826 % complete... training performance:
[bin,cts] tp: [0.00618,0.04191]
[bin,cts] fp: [0.06366,0.37935]
[bin,cts] fn: [0.09382,0.05809]
[bin,cts,tgt] fp/fn: [   0.67853,   6.53065,   0.49000]
bin pr:0.08849
bin rc:0.06180
fp wgt: 0.30506
Epoch 59.92317541613317 % complete... training performance:
[bin,cts] tp: [0.00620,0.04176]
[bin,cts] fp: [0.06398,0.37807]
[bin,cts] fn: [0.09380,0.05824]
[bin,cts,tgt] fp/fn: [   0.68209,   6.49136,   0.49000]
bin pr:0.08834
b

Epoch 89.88476312419974 % complete... training performance:
[bin,cts] tp: [0.00750,0.04352]
[bin,cts] fp: [0.07588,0.39373]
[bin,cts] fn: [0.09250,0.05648]
[bin,cts,tgt] fp/fn: [   0.82032,   6.97059,   0.49000]
bin pr:0.08995
bin rc:0.07500
fp wgt: 0.07112
Epoch 91.1651728553137 % complete... training performance:
[bin,cts] tp: [0.00738,0.04341]
[bin,cts] fp: [0.07434,0.39275]
[bin,cts] fn: [0.09262,0.05659]
[bin,cts,tgt] fp/fn: [   0.80263,   6.93982,   0.49000]
bin pr:0.09031
bin rc:0.07380
fp wgt: 0.07292
Epoch 99.8719590268886 % complete... training performance:
[bin,cts] tp: [0.00692,0.04298]
[bin,cts] fp: [0.06986,0.38885]
[bin,cts] fn: [0.09308,0.05702]
[bin,cts,tgt] fp/fn: [   0.75054,   6.81964,   0.49000]
bin pr:0.09013
bin rc:0.06920
fp wgt: 0.05508
...done!
Training performance:
[bin,cts] tp: [0.00692,0.04298]
[bin,cts] fp: [0.06986,0.38885]
[bin,cts] fn: [0.09308,0.05702]
[bin,cts,tgt] fp/fn: [   0.75054,   6.81964,   0.49000]
bin pr:0.09013
bin rc:0.06920
fp wgt: 0.05508

Epoch 21.254801536491676 % complete... training performance:
[bin,cts] tp: [0.00650,0.04334]
[bin,cts] fp: [0.06496,0.39157]
[bin,cts] fn: [0.09350,0.05666]
[bin,cts,tgt] fp/fn: [   0.69476,   6.91099,   0.49000]
bin pr:0.09096
bin rc:0.06500
fp wgt: -0.39855
Epoch 29.961587708066585 % complete... training performance:
[bin,cts] tp: [0.00954,0.04539]
[bin,cts] fp: [0.09552,0.40997]
[bin,cts] fn: [0.09046,0.05461]
[bin,cts,tgt] fp/fn: [   1.05594,   7.50694,   0.49000]
bin pr:0.09081
bin rc:0.09540
fp wgt: 0.00722
Epoch 31.241997439180537 % complete... training performance:
[bin,cts] tp: [0.00960,0.04543]
[bin,cts] fp: [0.09620,0.41036]
[bin,cts] fn: [0.09040,0.05457]
[bin,cts,tgt] fp/fn: [   1.06416,   7.52037,   0.49000]
bin pr:0.09074
bin rc:0.09600
fp wgt: 0.05336
Epoch 39.94878361075544 % complete... training performance:
[bin,cts] tp: [0.00822,0.04470]
[bin,cts] fp: [0.08438,0.40395]
[bin,cts] fn: [0.09178,0.05530]
[bin,cts,tgt] fp/fn: [   0.91937,   7.30444,   0.49000]
bin pr:0.0

Epoch 69.91037131882202 % complete... training performance:
[bin,cts] tp: [0.01072,0.04670]
[bin,cts] fp: [0.10924,0.42232]
[bin,cts] fn: [0.08928,0.05330]
[bin,cts,tgt] fp/fn: [   1.22357,   7.92355,   0.49000]
bin pr:0.08936
bin rc:0.10720
fp wgt: -0.15099
Epoch 71.19078104993598 % complete... training performance:
[bin,cts] tp: [0.01094,0.04683]
[bin,cts] fp: [0.11140,0.42349]
[bin,cts] fn: [0.08906,0.05317]
[bin,cts,tgt] fp/fn: [   1.25084,   7.96471,   0.49000]
bin pr:0.08942
bin rc:0.10940
fp wgt: -0.05398
Epoch 79.89756722151088 % complete... training performance:
[bin,cts] tp: [0.00940,0.04611]
[bin,cts] fp: [0.09706,0.41681]
[bin,cts] fn: [0.09060,0.05389]
[bin,cts,tgt] fp/fn: [   1.07130,   7.73479,   0.49000]
bin pr:0.08830
bin rc:0.09400
fp wgt: -0.09482
Epoch 81.17797695262485 % complete... training performance:
[bin,cts] tp: [0.00952,0.04613]
[bin,cts] fp: [0.09738,0.41695]
[bin,cts] fn: [0.09048,0.05387]
[bin,cts,tgt] fp/fn: [   1.07626,   7.74001,   0.49000]
bin pr:0.08

Epoch 1.2804097311139564 % complete... training performance:
[bin,cts] tp: [0.00662,0.04441]
[bin,cts] fp: [0.06772,0.40099]
[bin,cts] fn: [0.09338,0.05559]
[bin,cts,tgt] fp/fn: [   0.72521,   7.21394,   0.49000]
bin pr:0.08905
bin rc:0.06620
fp wgt: 0.08001
Epoch 9.98719590268886 % complete... training performance:
[bin,cts] tp: [0.00596,0.04397]
[bin,cts] fp: [0.06022,0.39685]
[bin,cts] fn: [0.09404,0.05603]
[bin,cts,tgt] fp/fn: [   0.64037,   7.08307,   0.49000]
bin pr:0.09006
bin rc:0.05960
fp wgt: -0.04240
Epoch 11.267605633802818 % complete... training performance:
[bin,cts] tp: [0.00574,0.04382]
[bin,cts] fp: [0.05760,0.39545]
[bin,cts] fn: [0.09426,0.05618]
[bin,cts,tgt] fp/fn: [   0.61108,   7.03918,   0.49000]
bin pr:0.09062
bin rc:0.05740
fp wgt: -0.01478
Epoch 19.97439180537772 % complete... training performance:
[bin,cts] tp: [0.00614,0.04424]
[bin,cts] fp: [0.06240,0.39925]
[bin,cts] fn: [0.09386,0.05576]
[bin,cts,tgt] fp/fn: [   0.66482,   7.16013,   0.49000]
bin pr:0.08

KeyboardInterrupt: 