In [1]:
!ls ~/data/cifar-10-python/cifar-10-batches-py/


batches.meta  data_batch_2  data_batch_4  readme.html
data_batch_1  data_batch_3  data_batch_5  test_batch


In [2]:
from pickle import load
from numpy import concatenate,array,float32
from pathlib import Path
labs=[]
data=[]
for f in [str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/data_batch_'+str(i) for i in range(1,6)]:
  with open(f,'rb') as fd:
    raw=load(fd,encoding='bytes')
    data.append(raw[b'data'])
    labs.append(array(raw[b'labels']))

X=concatenate(data)
y=(concatenate(labs)==0).astype(float32)
    
with open(str(Path.home())+'/data/cifar-10-python/cifar-10-batches-py/test_batch','rb') as fd:
  raw=load(fd,encoding='bytes')
  X_test=raw[b'data']
  y_test=(array(raw[b'labels'])==0).astype(float32)
  

print('Each batch has data shape:',raw[b'data'].shape)
print('Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image')



Each batch has data shape: (10000, 3072)
Note 3072==32*32*3 is the number of bytes for each 3 channel 32 by 32 byte array image


In [3]:
print(X[:10])
print(y[:10])

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 28  30  33 ... 100  99  96]
 [134 131 128 ... 136 137 138]
 [125 110 102 ...  82  84  86]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
'''from cal.jaxn import bin_optimiser
hlp=bin_optimiser(X.shape[1],kappa=.99,beta=2)
hlp.bench(X_test,y_test)
hlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)
hlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)
hlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)
hlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)
hlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)
hlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)'''

'from cal.jaxn import bin_optimiser\nhlp=bin_optimiser(X.shape[1],kappa=.99,beta=2)\nhlp.bench(X_test,y_test)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)\nhlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)'

In [5]:
from cal.jaxn import bin_optimiser,mk_nlp_infer,mk_nlp_init_params
hlp=bin_optimiser(X.shape[1],kappa=.99,beta=2,implementation=mk_nlp_infer(),init_params=mk_nlp_init_params())
hlp.bench(X_test,y_test)
hlp.run_epochs(X,y,X_test,y_test,batch_size=512,n_epochs=800)
hlp.run_epochs(X,y,X_test,y_test,batch_size=256,n_epochs=400)
hlp.run_epochs(X,y,X_test,y_test,batch_size=128,n_epochs=200)
hlp.run_epochs(X,y,X_test,y_test,batch_size=64,n_epochs=100)
hlp.run_epochs(X,y,X_test,y_test,batch_size=32,n_epochs=50)
hlp.run_epochs(X,y,X_test,y_test,batch_size=16,n_epochs=25)

[bin,cts] tp: [0.10000,0.09525]
[bin,cts] fp: [0.90000,0.85714]
[bin,cts] fn: [0.00000,0.00475]
[bin,cts,tgt] fp/fn: [       inf, 180.62953,   4.00000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 0.00000
Beginning epoch 1 ...
Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.10000,0.09515]
[bin,cts] fp: [0.90000,0.85618]
[bin,cts] fn: [0.00000,0.00485]
[bin,cts,tgt] fp/fn: [       inf, 176.62125,   4.00000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 0.46094
Epoch 9.278350515463918 % complete... training performance:
[bin,cts] tp: [0.10000,0.09271]
[bin,cts] fp: [0.90000,0.83418]
[bin,cts] fn: [0.00000,0.00729]
[bin,cts,tgt] fp/fn: [       inf, 114.44553,   4.00000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 4.40556
Epoch 18.556701030927837 % complete... training performance:
[bin,cts] tp: [0.10000,0.08823]
[bin,cts] fp: [0.90000,0.79390]
[bin,cts] fn: [0.00000,0.01177]
[bin,cts,tgt] fp/fn: [       inf,  67.47443,   4.00000]
bin pr:0.10000
bin rc:1.00000
fp wgt: 8.01087
Epoch 27.8350515463

Epoch 55.670103092783506 % complete... training performance:
[bin,cts] tp: [0.00000,0.01001]
[bin,cts] fp: [0.00000,0.09040]
[bin,cts] fn: [0.10000,0.08999]
[bin,cts,tgt] fp/fn: [   0.00000,   1.00456,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -11.01838
Epoch 64.94845360824742 % complete... training performance:
[bin,cts] tp: [0.00000,0.01010]
[bin,cts] fp: [0.00000,0.09120]
[bin,cts] fn: [0.10000,0.08990]
[bin,cts,tgt] fp/fn: [   0.00000,   1.01445,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -11.48074
Epoch 74.22680412371135 % complete... training performance:
[bin,cts] tp: [0.00000,0.01019]
[bin,cts] fp: [0.00000,0.09202]
[bin,cts] fn: [0.10000,0.08981]
[bin,cts,tgt] fp/fn: [   0.00000,   1.02464,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -11.89894
Epoch 83.50515463917526 % complete... training performance:
[bin,cts] tp: [0.00000,0.01028]
[bin,cts] fp: [0.00000,0.09286]
[bin,cts] fn: [0.10000,0.08972]
[bin,cts,tgt] fp/fn: [   0.00000,   1.03500,   4.00000]
bin pr:nan
bin rc:0

Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.00000,0.01316]
[bin,cts] fp: [0.00000,0.11881]
[bin,cts] fn: [0.10000,0.08684]
[bin,cts,tgt] fp/fn: [   0.00000,   1.36811,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -15.81122
Epoch 9.278350515463918 % complete... training performance:
[bin,cts] tp: [0.00000,0.01332]
[bin,cts] fp: [0.00000,0.12029]
[bin,cts] fn: [0.10000,0.08668]
[bin,cts,tgt] fp/fn: [   0.00000,   1.38781,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -15.80243
Epoch 18.556701030927837 % complete... training performance:
[bin,cts] tp: [0.00000,0.01349]
[bin,cts] fp: [0.00000,0.12178]
[bin,cts] fn: [0.10000,0.08651]
[bin,cts,tgt] fp/fn: [   0.00000,   1.40775,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -15.78709
Epoch 27.835051546391753 % complete... training performance:
[bin,cts] tp: [0.00000,0.01366]
[bin,cts] fp: [0.00000,0.12331]
[bin,cts] fn: [0.10000,0.08634]
[bin,cts,tgt] fp/fn: [   0.00000,   1.42816,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt

Epoch 64.94845360824742 % complete... training performance:
[bin,cts] tp: [0.00000,0.02037]
[bin,cts] fp: [0.00000,0.18379]
[bin,cts] fn: [0.10000,0.07963]
[bin,cts,tgt] fp/fn: [   0.00000,   2.30792,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -16.15147
Epoch 74.22680412371135 % complete... training performance:
[bin,cts] tp: [0.00000,0.02076]
[bin,cts] fp: [0.00000,0.18735]
[bin,cts] fn: [0.10000,0.07924]
[bin,cts,tgt] fp/fn: [   0.00000,   2.36435,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -16.16574
Epoch 83.50515463917526 % complete... training performance:
[bin,cts] tp: [0.00000,0.02117]
[bin,cts] fp: [0.00000,0.19101]
[bin,cts] fn: [0.10000,0.07883]
[bin,cts,tgt] fp/fn: [   0.00000,   2.42300,   4.00000]
bin pr:nan
bin rc:0.00000
fp wgt: -16.19101
Epoch 92.78350515463917 % complete... training performance:
[bin,cts] tp: [0.00000,0.02159]
[bin,cts] fp: [0.00000,0.19485]
[bin,cts] fn: [0.10000,0.07841]
[bin,cts,tgt] fp/fn: [   0.00000,   2.48515,   4.00000]
bin pr:nan
bin rc:0.

Epoch 9.278350515463918 % complete... training performance:
[bin,cts] tp: [0.00042,0.03671]
[bin,cts] fp: [0.00520,0.33086]
[bin,cts] fn: [0.09958,0.06329]
[bin,cts,tgt] fp/fn: [   0.05222,   5.22732,   4.00000]
bin pr:0.07473
bin rc:0.00420
fp wgt: -16.16858
Epoch 18.556701030927837 % complete... training performance:
[bin,cts] tp: [0.00054,0.03761]
[bin,cts] fp: [0.00730,0.33897]
[bin,cts] fn: [0.09946,0.06239]
[bin,cts,tgt] fp/fn: [   0.07340,   5.43290,   4.00000]
bin pr:0.06888
bin rc:0.00540
fp wgt: -16.04077
Epoch 27.835051546391753 % complete... training performance:
[bin,cts] tp: [0.00078,0.03853]
[bin,cts] fp: [0.01030,0.34723]
[bin,cts] fn: [0.09922,0.06147]
[bin,cts,tgt] fp/fn: [   0.10381,   5.64839,   4.00000]
bin pr:0.07040
bin rc:0.00780
fp wgt: -15.93950
Epoch 37.11340206185567 % complete... training performance:
[bin,cts] tp: [0.00134,0.03947]
[bin,cts] fp: [0.01404,0.35574]
[bin,cts] fn: [0.09866,0.06053]
[bin,cts,tgt] fp/fn: [   0.14231,   5.87740,   4.00000]
bin pr

Epoch 64.94845360824742 % complete... training performance:
[bin,cts] tp: [0.00004,0.03157]
[bin,cts] fp: [0.00082,0.28466]
[bin,cts] fn: [0.09996,0.06843]
[bin,cts,tgt] fp/fn: [   0.00820,   4.16003,   4.00000]
bin pr:0.04651
bin rc:0.00040
fp wgt: -8.34304
Epoch 74.22680412371135 % complete... training performance:
[bin,cts] tp: [0.00006,0.03224]
[bin,cts] fp: [0.00106,0.29070]
[bin,cts] fn: [0.09994,0.06776]
[bin,cts,tgt] fp/fn: [   0.01061,   4.29039,   4.00000]
bin pr:0.05357
bin rc:0.00060
fp wgt: -9.03260
Epoch 83.50515463917526 % complete... training performance:
[bin,cts] tp: [0.00008,0.03293]
[bin,cts] fp: [0.00150,0.29693]
[bin,cts] fn: [0.09992,0.06707]
[bin,cts,tgt] fp/fn: [   0.01501,   4.42750,   4.00000]
bin pr:0.05063
bin rc:0.00080
fp wgt: -9.67476
Epoch 92.78350515463917 % complete... training performance:
[bin,cts] tp: [0.00010,0.03366]
[bin,cts] fp: [0.00200,0.30344]
[bin,cts] fn: [0.09990,0.06634]
[bin,cts,tgt] fp/fn: [   0.02002,   4.57384,   4.00000]
bin pr:0.04

Epoch 9.278350515463918 % complete... training performance:
[bin,cts] tp: [0.02268,0.04807]
[bin,cts] fp: [0.20642,0.43299]
[bin,cts] fn: [0.07732,0.05193]
[bin,cts,tgt] fp/fn: [   2.66968,   8.33865,   4.00000]
bin pr:0.09900
bin rc:0.22680
fp wgt: 1.67781
Epoch 18.556701030927837 % complete... training performance:
[bin,cts] tp: [0.00384,0.04191]
[bin,cts] fp: [0.03730,0.37759]
[bin,cts] fn: [0.09616,0.05809]
[bin,cts,tgt] fp/fn: [   0.38790,   6.49964,   4.00000]
bin pr:0.09334
bin rc:0.03840
fp wgt: 0.92573
Epoch 27.835051546391753 % complete... training performance:
[bin,cts] tp: [0.00050,0.03639]
[bin,cts] fp: [0.00656,0.32805]
[bin,cts] fn: [0.09950,0.06361]
[bin,cts,tgt] fp/fn: [   0.06593,   5.15759,   4.00000]
bin pr:0.07082
bin rc:0.00500
fp wgt: -0.33294
Epoch 37.11340206185567 % complete... training performance:
[bin,cts] tp: [0.00008,0.03293]
[bin,cts] fp: [0.00186,0.29690]
[bin,cts] fn: [0.09992,0.06707]
[bin,cts,tgt] fp/fn: [   0.01861,   4.42662,   4.00000]
bin pr:0.04

Epoch 64.94845360824742 % complete... training performance:
[bin,cts] tp: [0.01818,0.04731]
[bin,cts] fp: [0.17036,0.42613]
[bin,cts] fn: [0.08182,0.05269]
[bin,cts,tgt] fp/fn: [   2.08213,   8.08745,   4.00000]
bin pr:0.09643
bin rc:0.18180
fp wgt: -10.61176
Epoch 74.22680412371135 % complete... training performance:
[bin,cts] tp: [0.02414,0.04822]
[bin,cts] fp: [0.21914,0.43434]
[bin,cts] fn: [0.07586,0.05178]
[bin,cts,tgt] fp/fn: [   2.88874,   8.38863,   4.00000]
bin pr:0.09923
bin rc:0.24140
fp wgt: -9.74254
Epoch 83.50515463917526 % complete... training performance:
[bin,cts] tp: [0.03130,0.04914]
[bin,cts] fp: [0.28332,0.44258]
[bin,cts] fn: [0.06870,0.05086]
[bin,cts,tgt] fp/fn: [   4.12402,   8.70208,   4.00000]
bin pr:0.09949
bin rc:0.31300
fp wgt: -8.69128
Epoch 92.78350515463917 % complete... training performance:
[bin,cts] tp: [0.04162,0.05008]
[bin,cts] fp: [0.36466,0.45099]
[bin,cts] fn: [0.05838,0.04992]
[bin,cts,tgt] fp/fn: [   6.24632,   9.03389,   4.00000]
bin pr:0.1

Epoch 9.278350515463918 % complete... training performance:
[bin,cts] tp: [0.00568,0.04249]
[bin,cts] fp: [0.05568,0.38279]
[bin,cts] fn: [0.09432,0.05751]
[bin,cts,tgt] fp/fn: [   0.59033,   6.65573,   4.00000]
bin pr:0.09257
bin rc:0.05680
fp wgt: -10.86386
Epoch 18.556701030927837 % complete... training performance:
[bin,cts] tp: [0.00716,0.04331]
[bin,cts] fp: [0.06708,0.39020]
[bin,cts] fn: [0.09284,0.05669]
[bin,cts,tgt] fp/fn: [   0.72253,   6.88312,   4.00000]
bin pr:0.09644
bin rc:0.07160
fp wgt: -10.84110
Epoch 27.835051546391753 % complete... training performance:
[bin,cts] tp: [0.00868,0.04414]
[bin,cts] fp: [0.08134,0.39765]
[bin,cts] fn: [0.09132,0.05586]
[bin,cts,tgt] fp/fn: [   0.89071,   7.11889,   4.00000]
bin pr:0.09642
bin rc:0.08680
fp wgt: -10.79120
Epoch 37.11340206185567 % complete... training performance:
[bin,cts] tp: [0.01050,0.04499]
[bin,cts] fp: [0.09906,0.40526]
[bin,cts] fn: [0.08950,0.05501]
[bin,cts,tgt] fp/fn: [   1.10682,   7.36670,   4.00000]
bin pr

Epoch 74.22680412371135 % complete... training performance:
[bin,cts] tp: [0.00458,0.04076]
[bin,cts] fp: [0.04392,0.36725]
[bin,cts] fn: [0.09542,0.05924]
[bin,cts,tgt] fp/fn: [   0.46028,   6.19889,   4.00000]
bin pr:0.09443
bin rc:0.04580
fp wgt: -9.76112
Epoch 83.50515463917526 % complete... training performance:
[bin,cts] tp: [0.00544,0.04157]
[bin,cts] fp: [0.05324,0.37458]
[bin,cts] fn: [0.09456,0.05843]
[bin,cts,tgt] fp/fn: [   0.56303,   6.41094,   4.00000]
bin pr:0.09271
bin rc:0.05440
fp wgt: -9.86153
Epoch 92.78350515463917 % complete... training performance:
[bin,cts] tp: [0.00682,0.04241]
[bin,cts] fp: [0.06384,0.38214]
[bin,cts] fn: [0.09318,0.05759]
[bin,cts,tgt] fp/fn: [   0.68513,   6.63590,   4.00000]
bin pr:0.09652
bin rc:0.06820
fp wgt: -9.95623
...done!
Training performance:
[bin,cts] tp: [0.00766,0.04298]
[bin,cts] fp: [0.07198,0.38727]
[bin,cts] fn: [0.09234,0.05702]
[bin,cts,tgt] fp/fn: [   0.77951,   6.79233,   4.00000]
bin pr:0.09618
bin rc:0.07660
fp wgt: -9

Epoch 18.556701030927837 % complete... training performance:
[bin,cts] tp: [0.00234,0.03769]
[bin,cts] fp: [0.02432,0.33973]
[bin,cts] fn: [0.09766,0.06231]
[bin,cts,tgt] fp/fn: [   0.24903,   5.45222,   4.00000]
bin pr:0.08777
bin rc:0.02340
fp wgt: -8.22489
Epoch 27.835051546391753 % complete... training performance:
[bin,cts] tp: [0.00296,0.03844]
[bin,cts] fp: [0.02976,0.34643]
[bin,cts] fn: [0.09704,0.06156]
[bin,cts,tgt] fp/fn: [   0.30668,   5.62734,   4.00000]
bin pr:0.09046
bin rc:0.02960
fp wgt: -8.57880
Epoch 37.11340206185567 % complete... training performance:
[bin,cts] tp: [0.00372,0.03921]
[bin,cts] fp: [0.03666,0.35334]
[bin,cts] fn: [0.09628,0.06079]
[bin,cts,tgt] fp/fn: [   0.38076,   5.81202,   4.00000]
bin pr:0.09212
bin rc:0.03720
fp wgt: -8.88320
Epoch 46.391752577319586 % complete... training performance:
[bin,cts] tp: [0.00454,0.04000]
[bin,cts] fp: [0.04452,0.36046]
[bin,cts] fn: [0.09546,0.06000]
[bin,cts,tgt] fp/fn: [   0.46637,   6.00766,   4.00000]
bin pr:0

Epoch 83.50515463917526 % complete... training performance:
[bin,cts] tp: [0.00304,0.03767]
[bin,cts] fp: [0.03108,0.33955]
[bin,cts] fn: [0.09696,0.06233]
[bin,cts,tgt] fp/fn: [   0.32054,   5.44726,   4.00000]
bin pr:0.08910
bin rc:0.03040
fp wgt: -6.84372
Epoch 92.78350515463917 % complete... training performance:
[bin,cts] tp: [0.00380,0.03845]
[bin,cts] fp: [0.03782,0.34661]
[bin,cts] fn: [0.09620,0.06155]
[bin,cts,tgt] fp/fn: [   0.39314,   5.63157,   4.00000]
bin pr:0.09130
bin rc:0.03800
fp wgt: -7.28734
...done!
Training performance:
[bin,cts] tp: [0.00428,0.03899]
[bin,cts] fp: [0.04234,0.35146]
[bin,cts] fn: [0.09572,0.06101]
[bin,cts,tgt] fp/fn: [   0.44233,   5.76110,   4.00000]
bin pr:0.09181
bin rc:0.04280
fp wgt: -7.52645
Testing performance:
[bin,cts] tp: [0.00440,0.03881]
[bin,cts] fp: [0.04140,0.35132]
[bin,cts] fn: [0.09560,0.06119]
[bin,cts,tgt] fp/fn: [   0.43305,   5.74143,   4.00000]
bin pr:0.09607
bin rc:0.04400
fp wgt: -7.52645
Beginning epoch 29 ...
Epoch 0.0

Epoch 27.835051546391753 % complete... training performance:
[bin,cts] tp: [0.00330,0.03711]
[bin,cts] fp: [0.03396,0.33461]
[bin,cts] fn: [0.09670,0.06289]
[bin,cts,tgt] fp/fn: [   0.35119,   5.32069,   4.00000]
bin pr:0.08857
bin rc:0.03300
fp wgt: -5.59202
Epoch 37.11340206185567 % complete... training performance:
[bin,cts] tp: [0.00400,0.03784]
[bin,cts] fp: [0.03972,0.34116]
[bin,cts] fn: [0.09600,0.06216]
[bin,cts,tgt] fp/fn: [   0.41375,   5.48832,   4.00000]
bin pr:0.09149
bin rc:0.04000
fp wgt: -6.10968
Epoch 46.391752577319586 % complete... training performance:
[bin,cts] tp: [0.00488,0.03862]
[bin,cts] fp: [0.04718,0.34821]
[bin,cts] fn: [0.09512,0.06138]
[bin,cts,tgt] fp/fn: [   0.49601,   5.67342,   4.00000]
bin pr:0.09374
bin rc:0.04880
fp wgt: -6.57653
Epoch 55.670103092783506 % complete... training performance:
[bin,cts] tp: [0.00600,0.03945]
[bin,cts] fp: [0.05690,0.35557]
[bin,cts] fn: [0.09400,0.06055]
[bin,cts,tgt] fp/fn: [   0.60532,   5.87195,   4.00000]
bin pr:0

Epoch 92.78350515463917 % complete... training performance:
[bin,cts] tp: [0.00588,0.03849]
[bin,cts] fp: [0.05554,0.34706]
[bin,cts] fn: [0.09412,0.06151]
[bin,cts,tgt] fp/fn: [   0.59010,   5.64239,   4.00000]
bin pr:0.09573
bin rc:0.05880
fp wgt: -6.14669
...done!
Training performance:
[bin,cts] tp: [0.00666,0.03906]
[bin,cts] fp: [0.06226,0.35220]
[bin,cts] fn: [0.09334,0.06094]
[bin,cts,tgt] fp/fn: [   0.66702,   5.77979,   4.00000]
bin pr:0.09663
bin rc:0.06660
fp wgt: -6.34973
Testing performance:
[bin,cts] tp: [0.00600,0.03882]
[bin,cts] fp: [0.06180,0.35204]
[bin,cts] fn: [0.09400,0.06118]
[bin,cts,tgt] fp/fn: [   0.65745,   5.75414,   4.00000]
bin pr:0.08850
bin rc:0.06000
fp wgt: -6.34973
Beginning epoch 34 ...
Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.00670,0.03916]
[bin,cts] fp: [0.06342,0.35306]
[bin,cts] fn: [0.09330,0.06084]
[bin,cts,tgt] fp/fn: [   0.67974,   5.80313,   4.00000]
bin pr:0.09555
bin rc:0.06700
fp wgt: -6.37021
Epoch 9.278350515463918

Epoch 37.11340206185567 % complete... training performance:
[bin,cts] tp: [0.00756,0.03905]
[bin,cts] fp: [0.07146,0.35216]
[bin,cts] fn: [0.09244,0.06095]
[bin,cts,tgt] fp/fn: [   0.77304,   5.77803,   4.00000]
bin pr:0.09567
bin rc:0.07560
fp wgt: -5.47155
Epoch 46.391752577319586 % complete... training performance:
[bin,cts] tp: [0.00882,0.03993]
[bin,cts] fp: [0.08070,0.36001]
[bin,cts] fn: [0.09118,0.06007]
[bin,cts,tgt] fp/fn: [   0.88506,   5.99282,   4.00000]
bin pr:0.09853
bin rc:0.08820
fp wgt: -5.69318
Epoch 55.670103092783506 % complete... training performance:
[bin,cts] tp: [0.01004,0.04083]
[bin,cts] fp: [0.09206,0.36815]
[bin,cts] fn: [0.08996,0.05917]
[bin,cts,tgt] fp/fn: [   1.02334,   6.22239,   4.00000]
bin pr:0.09833
bin rc:0.10040
fp wgt: -5.83760
Epoch 64.94845360824742 % complete... training performance:
[bin,cts] tp: [0.01134,0.04176]
[bin,cts] fp: [0.10488,0.37647]
[bin,cts] fn: [0.08866,0.05824]
[bin,cts,tgt] fp/fn: [   1.18295,   6.46426,   4.00000]
bin pr:0.

...done!
Training performance:
[bin,cts] tp: [0.01400,0.04269]
[bin,cts] fp: [0.12682,0.38489]
[bin,cts] fn: [0.08600,0.05731]
[bin,cts,tgt] fp/fn: [   1.47465,   6.71614,   4.00000]
bin pr:0.09942
bin rc:0.14000
fp wgt: -4.92023
Testing performance:
[bin,cts] tp: [0.01180,0.04236]
[bin,cts] fp: [0.12830,0.38472]
[bin,cts] fn: [0.08820,0.05764]
[bin,cts,tgt] fp/fn: [   1.45465,   6.67451,   4.00000]
bin pr:0.08423
bin rc:0.11800
fp wgt: -4.92023
Beginning epoch 39 ...
Epoch 0.0 % complete... training performance:
[bin,cts] tp: [0.01428,0.04280]
[bin,cts] fp: [0.12836,0.38586]
[bin,cts] fn: [0.08572,0.05720]
[bin,cts,tgt] fp/fn: [   1.49743,   6.74585,   4.00000]
bin pr:0.10011
bin rc:0.14280
fp wgt: -4.90423
Epoch 9.278350515463918 % complete... training performance:
[bin,cts] tp: [0.01574,0.04376]
[bin,cts] fp: [0.14312,0.39448]
[bin,cts] fn: [0.08426,0.05624]
[bin,cts,tgt] fp/fn: [   1.69855,   7.01453,   4.00000]
bin pr:0.09908
bin rc:0.15740
fp wgt: -4.69881
Epoch 18.55670103092783

Epoch 46.391752577319586 % complete... training performance:
[bin,cts] tp: [0.01890,0.04514]
[bin,cts] fp: [0.17730,0.40686]
[bin,cts] fn: [0.08110,0.05486]
[bin,cts,tgt] fp/fn: [   2.18619,   7.41667,   4.00000]
bin pr:0.09633
bin rc:0.18900
fp wgt: -3.79100
Epoch 55.670103092783506 % complete... training performance:
[bin,cts] tp: [0.02108,0.04599]
[bin,cts] fp: [0.19504,0.41447]
[bin,cts] fn: [0.07892,0.05401]
[bin,cts,tgt] fp/fn: [   2.47136,   7.67439,   4.00000]
bin pr:0.09754
bin rc:0.21080
fp wgt: -3.53236
Epoch 64.94845360824742 % complete... training performance:
[bin,cts] tp: [0.02286,0.04676]
[bin,cts] fp: [0.21300,0.42136]
[bin,cts] fn: [0.07714,0.05324]
[bin,cts,tgt] fp/fn: [   2.76121,   7.91474,   4.00000]
bin pr:0.09692
bin rc:0.22860
fp wgt: -3.25749
Epoch 74.22680412371135 % complete... training performance:
[bin,cts] tp: [0.02492,0.04742]
[bin,cts] fp: [0.23092,0.42724]
[bin,cts] fn: [0.07508,0.05258]
[bin,cts,tgt] fp/fn: [   3.07565,   8.12528,   4.00000]
bin pr:0.

KeyboardInterrupt: 